CREATE TABLE USER (
    id IDENTITY NOT NULL PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    description VARCHAR(50),
)

CREATE TABLE ARTICLE (
    id IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    headline VARCHAR(100) NOT NULL,
    content VARCHAR NOT NULL,
    author BIGINT FOREIGN KEY REFERENCES(USER.id) NOT NULL,
    slug VARCHAR(100),
    addedAt TIMESTAMP,
);